export const START_LOADING = 'START_LOADING';
export const ADD_EXPENSE_SUCCESS = 'ADD_EXPENSE_SUCCESS';
export const LOADING_FAIL = 'LOADING_FAIL';
export const FETCH_EXPENSE_SUCCESS = 'FETCH_EXPENSE_SUCCESS';